<a href="https://colab.research.google.com/github/dilshvn/fcc-pytorch-for-DL/blob/main/PT_fcc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

pre-built DL models: from torch hub/torchvision.models

In [1]:
!nvidia-smi

Thu Jun 29 11:13:00 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   66C    P8    11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
import torch
print(torch.__version__)

2.0.1+cu118


In [6]:
t1 = torch.tensor(7)
t1

tensor(7)

In [5]:
t1.ndim

0

In [7]:
t1.item()

7

In [11]:
v1 = torch.tensor([7,7])
v1

tensor([7, 7])

In [12]:
v1.ndim

1

In [14]:
v1.shape

torch.Size([2])

In [7]:
m1 = torch.tensor([[7,8],[9,10]])
m1

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
m1.ndim

2

In [11]:
m1.shape

torch.Size([2, 2])

In [9]:
m1[0]

tensor([7, 8])

In [10]:
m1[1]

tensor([ 9, 10])

In [4]:
m2 = torch.tensor([[1,3],[2,3],[5,6]])
m2

tensor([[1, 3],
        [2, 3],
        [5, 6]])

In [5]:
m2.shape

torch.Size([3, 2])

In [12]:
m3 = torch.tensor([[[1,3],[2,3],[5,6]]])
m3

tensor([[[1, 3],
         [2, 3],
         [5, 6]]])

In [14]:
m3.ndim

3

In [15]:
m3.shape

torch.Size([1, 3, 2])

In [16]:
m3[0]

tensor([[1, 3],
        [2, 3],
        [5, 6]])

In [6]:
t1 = torch.rand(3,4)
t1

tensor([[0.9080, 0.3634, 0.9999, 0.7139],
        [0.3513, 0.1233, 0.4474, 0.3934],
        [0.2628, 0.0534, 0.6280, 0.5438]])

In [22]:
t1.ndim

2

In [23]:
t1[0]

tensor([0.0227, 0.0401, 0.9564, 0.7566])

In [24]:
t1[1]

tensor([0.8610, 0.5212, 0.3605, 0.8766])

In [25]:
t1[2]

tensor([0.2487, 0.6596, 0.0652, 0.2040])

In [2]:
 img = torch.rand(3,224,224)
 img.shape,img.ndim

(torch.Size([224, 224, 3]), 3)

In [3]:
img2 = torch.rand(1,3,224,224)
img2.shape,img2.ndim

(torch.Size([1, 3, 224, 224]), 4)

In [4]:
z1 = torch.zeros(3,4)
z1

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [7]:
z1*t1

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [8]:
w1 = torch.ones(3,4)
w1

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [9]:
w1.dtype

torch.float32

In [15]:
r1 = torch.range(0,10)
r1,r1.shape,r1.ndim

<ipython-input-15-b627c1db989b>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  r1 = torch.range(0,10)


(tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 torch.Size([11]),
 1)

In [16]:
r2 = torch.arange(10)
r2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
t1 = torch.zeros_like(r2)
t1

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
t1 = torch.tensor([3,4],dtype=None)
t1.dtype

torch.int64

In [23]:
t1 = torch.tensor([3,4],dtype=torch.float16)
t1.dtype,t1.device,t1.requires_grad

(torch.float16, device(type='cpu'), False)

In [24]:
t1 = torch.tensor([3,4],dtype=None,device=None,requires_grad=False)
t1.dtype,t1.device,t1.requires_grad

(torch.int64, device(type='cpu'), False)

In [28]:
t1 = t1.type(torch.float16)
t1.dtype,t1

(torch.float16, tensor([3., 4.], dtype=torch.float16))

In [2]:
t1 = torch.tensor([3,4],dtype=torch.float16)
t2 = torch.tensor([3,4],dtype=torch.float32)
t1*t2

tensor([ 9., 16.])

In [3]:
t1 = torch.tensor([3,4],dtype=torch.float16)
t2 = torch.tensor([3,4],dtype=torch.int8)
t1*t2

tensor([ 9., 16.], dtype=torch.float16)

In [4]:
t1 = torch.tensor([3,4],dtype=torch.long)
t2 = torch.tensor([3,4],dtype=torch.int8)
t1*t2

tensor([ 9, 16])

In [8]:
t1 = torch.rand(3,4)
t1,t1.dtype,t1.size(),t1.shape,t1.device

(tensor([[0.1923, 0.3631, 0.9528, 0.7176],
         [0.2994, 0.9684, 0.7104, 0.8377],
         [0.9090, 0.7404, 0.0775, 0.6959]]),
 torch.float32,
 torch.Size([3, 4]),
 torch.Size([3, 4]),
 device(type='cpu'))

In [4]:
t1 = torch.tensor([1,2,3])
t1 + 10

tensor([11, 12, 13])

In [5]:
t1*10

tensor([10, 20, 30])

In [6]:
t1-10

tensor([-9, -8, -7])

In [7]:
torch.mul(t1,10)

tensor([10, 20, 30])

In [8]:
torch.add(t1,10)

tensor([11, 12, 13])

In [9]:
torch.matmul(t1,t1)

tensor(14)

In [13]:
t1 = torch.rand(3,4)
t2 = torch.rand(4,3)

In [14]:
t1.shape,t2.shape

(torch.Size([3, 4]), torch.Size([4, 3]))

In [16]:
 %%time
 torch.matmul(t1,t2)

CPU times: user 378 µs, sys: 36 µs, total: 414 µs
Wall time: 291 µs


tensor([[1.1519, 0.2500, 1.3258],
        [1.1380, 0.3673, 1.2415],
        [1.3825, 0.4242, 1.4083]])

In [17]:
 %%time
 torch.mm(t1,t2)

CPU times: user 1.04 ms, sys: 4 µs, total: 1.04 ms
Wall time: 2.74 ms


tensor([[1.1519, 0.2500, 1.3258],
        [1.1380, 0.3673, 1.2415],
        [1.3825, 0.4242, 1.4083]])

In [18]:
t1 = torch.rand(3,4)
t2 = torch.rand(3,4)

In [19]:
t1,t2

(tensor([[0.2301, 0.0265, 0.3407, 0.7450],
         [0.1391, 0.0846, 0.9996, 0.8855],
         [0.3192, 0.4707, 0.5169, 0.3339]]),
 tensor([[0.1281, 0.6173, 0.1107, 0.6092],
         [0.6255, 0.9003, 0.9818, 0.5899],
         [0.4471, 0.9926, 0.1908, 0.3893]]))

In [20]:
t2.T

tensor([[0.1281, 0.6255, 0.4471],
        [0.6173, 0.9003, 0.9926],
        [0.1107, 0.9818, 0.1908],
        [0.6092, 0.5899, 0.3893]])

In [21]:
torch.mm(t1,t2)

RuntimeError: ignored

In [22]:
torch.mm(t1,t2.T)

tensor([[0.5374, 0.9417, 0.4842],
        [0.7202, 1.6669, 0.6815],
        [0.5921, 1.3280, 0.8386]])